Add Response.unauthorized (401) constructor
dart-lang/shelf pull request #262
Opened 2022-08-04 17:22 UTC by develogo

2022-08-05 19:55 UTC, kevmoo requested changes
Cool! Please add a changelog entry and bump the version to `1.4.0` – since this is adding new API!

2022-08-05 19:56 UTC, kevmoo commented on pkgs/shelf/lib/src/response.dart
> +  /// This indicates that the request is unauthorized due to invalid
invalid...what? Might want to fix this sentence, too!

2022-08-05 19:56 UTC, kevmoo commented on pkgs/shelf/test/response_test.dart
> +      expect(response.readAsString(), completion(equals('Unauthorized')));
A tiny bit redundant, but you should probably check the status code here, too!

2022-08-08 02:05 UTC, kevmoo commented
@develogo – please also update the pubspec version to match the changelog

2022-08-08 02:23 UTC, develogo commented
@kevmoo updated, sorry for the lack of attention

2022-08-08 03:14 UTC, kevmoo commented
> @kevmoo updated, sorry for the lack of attention

You're learning! No worries. Thanks for the contribution...

2022-08-08 03:14 UTC, kevmoo approved these changes

2022-08-08 03:24 UTC, merged